version: '3.8'

services:
  db:
    container_name: db
    image: postgres:17-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: maksuamet
      POSTGRES_USER: maksuamet
      POSTGRES_PASSWORD: ABParool1
    volumes:
      - ~/Documents/Maksuamet/db:/var/lib/postgresql/data

  spring-app:
    container_name: Maksuamet-app
    build:
      context: .
    image: maksuamet-app:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/maksuamet
      SPRING_DATASOURCE_USERNAME: maksuamet
      SPRING_DATASOURCE_PASSWORD: ABParool1
    depends_on:
      - db

volumes:
  db:
